### ISSUE TITLE
Initial positioning offset

### ISSUE THREAD

**Issue by SongJ11** [6-robot/jie_ware#1]
![2024-10-14 09-36-00屏幕截图](https://github.com/user-attachments/assets/dfbae37e-52b8-4d2f-8747-9c04b345078b)
Hello, when I replaced AMCL with the lidar LOC node and started the simulation environment and positioning node, there was a significant deviation between the initial and actual positions of the robot. I did not pull the robot back to its starting point using the 2D Pose Esimate in RVIZ.

**Comment by zhangwanjie** [comment]
Thank you for reporting this issue. I appreciate your contribution and pleased to inform you that the bug you reported has been fixed. 
Thank you again for your help in identifying this issue.

**Comment by SongJ11** [comment]
Thank you for the modification. Thank you again.

**Comment by SongJ11** [comment]
Hello, when testing a larger map, it causes OpenCV cropping to fail.

The error message is as follows:
OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/matrix.cpp, line 522
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/matrix.cpp:522: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat

`    // 按照有效区域对地图进行裁剪
    int new_half_width = abs(xMax - xMin)/2 + 50;
    int new_half_height = abs(yMax - yMin)/2 + 50;
    int new_origin_x = cen_x - new_half_width;
    int new_origin_y = cen_y - new_half_height;`
I modified this and tested it on the big map
`    int new_origin_x = abs(cen_x - new_half_width);
    int new_origin_y = abs(cen_y - new_half_height)`

Please test if it is correct,thanks.

**Comment by SongJ11** [comment]
Hello, I encountered the following error while testing the larger map:
`OpenCV Error: Assertion failed (0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows) in Mat, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/matrix.cpp, line 522
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/matrix.cpp:522: error: (-215) 0 <= roi.x && 0 <= roi.width && roi.x + roi.width <= m.cols && 0 <= roi.y && 0 <= roi.height && roi.y + roi.height <= m.rows in function Mat`

![捕获](https://github.com/user-attachments/assets/d0f66ad5-29e7-4189-af4d-5d03245e5820)
`image: gmapping_map.pgm
resolution: 0.050000
origin: [-20.000000, -20.000000, 0.000000]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196`

I modified the following code and the map above became normal:
`    int new_origin_x = cen_x - new_half_width;
    int new_origin_y = cen_y - new_half_height;`
 to
`    int new_origin_x = abs(cen_x - new_half_width);
    int new_origin_y = abs(cen_y - new_half_height);`

However, when I switched to another environment map (as shown in the picture below), the error message appeared again.
![捕获2](https://github.com/user-attachments/assets/87a40371-8301-497c-88cb-ea24b36efaa0)
`image: map.pgm
resolution: 0.050000
origin: [-17.065804, -16.746602, 0.000000]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196
`
Once again, we invite you to review the issue. Thank you.

**Comment by zhangwanjie** [comment]
Thank you for addressing this issue. It may have been resolved now. Could you please test it again? Feel free to provide feedback if you encounter any issues.

**Comment by SongJ11** [comment]
Okay, thanks.
